"""compas_convert."""


def _get_version():  # type: () -> str
    # from https://smarie.github.io/python-getversion/#package-versioning-best-practices
    # and setuptools_scm docs
    try:
        # import from _version.py generated by setuptools_scm during release
        from ._version import version

        return version
    except ImportError:
        try:
            from importlib.metadata import version  # type: ignore [no-redef]

            return version("rapid-clay-formations-fab")  # type: ignore [operator]
        except ImportError:
            try:
                from importlib_metadata import version  # type: ignore [no-redef]

                return version("rapid-clay-formations-fab")  # type: ignore [operator]
            except ImportError:
                pass

    return "src"


__author__ = "Anton Tetov Johansson"
__license__ = "MIT License"
__email__ = "anton@tetov.xyz"
__version__ = _get_version()
__all_plugins__ = ["compas_convert.rhino.install"]
