name: Test, build, publish docs and release

on:
  push:
    tags:
      - v*
    branches-ignore:
      - "gh-pages"

jobs:
  build-and-test:
    name: Install, test, build package and build docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel  # https://stackoverflow.com/questions/34819221
          python -m pip install cython --install-option='--no-cython-compile'
          python -m pip install --no-cache-dir -e .[dev]

      # - name: Test import
      #   run: python -m compas_convert

      - name: Test
        run: invoke test

      - name: Build docs
        run: invoke docs

      - name: Build package
        run: invoke build

  build-ghusercomponents:
    name: Test building ghuser components
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Need IPY for compas-actions.ghpython_components
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Install IronPython
        run: |
          choco install ironpython --version=2.7.8.1

      - name: Install
        run: |
          pip install --upgrade pip
          pip install wheel  # https://stackoverflow.com/questions/34819221
          pip install cython --install-option='--no-cython-compile'
          python -m pip install --no-cache-dir -e .[dev]

      - name: 🦗 Build grasshopper components
        uses: compas-dev/compas-actions.ghpython_components@v1
        with:
          source: src/compas_convert/rhino/grasshopper_components
          target: src/compas_convert/rhino/grasshopper_components/ghuser

  publish:
    name: Publish package
    if: startsWith( github.ref, 'refs/tags/v')
    needs:
      - build-and-test
      - build-ghusercomponents
    runs-on: windows-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install
        run: |
          pip install --upgrade pip
          pip install wheel  # https://stackoverflow.com/questions/34819221
          pip install cython --install-option='--no-cython-compile'
          python -m pip install --no-cache-dir -e .[dev]

      # Need IPY for compas-actions.ghpython_components
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Install IronPython
        run: |
          choco install ironpython --version=2.7.8.1

      - name: 🦗 Build grasshopper components
        uses: compas-dev/compas-actions.ghpython_components@v1
        with:
          source: src/compas_convert/rhino/grasshopper_components
          target: src/compas_convert/rhino/grasshopper_components/ghuser

      - name: Build package
        run: invoke build

      - name: Create GitHub release and upload assets
        uses: softprops/action-gh-release@fb0163a75bee697a9cfec2c931801de7c7f10042
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
